function FormatDates(val) {
  var dt = new Date(parseInt(val)*1000);
  return dt.format('d.m.y H:i')
}

TEXTS={
"Yes":"Да",
"No":"Нет",

"Exit":"Выход",
"CloseAll":"Закрыть все вкладки",
"Save":"Сохранить",
"Refresh":"Обновить",
"Open":"Раскрыть",
"Collapse":"Свернуть",
"Close":"Закрыть",
"Garb":"Мусорная корзина",

"Preview":"Просмотр",
"PreviewHint":"Открыть страницу предварительного просмотра",

"Settings":"Панель управления",
"Moduls":"Web-сервисы",
"Structure":"Структура",
"Programms":"Программы",
"Page":"Страница",
"Desktop":"Рабочий стол",
"Editor":"Редактор",
"Help":"Справка",
"AddNodeText":"Введите название страницы",
"AddNodeDefaultText":"Новая страница",
"DeleteNodeText":"Удалить раздел?",
"DeleteNodesText":"Удалить выделенные разделы?",
"PublicationOk":"Публикация завершена успешно.",
"ClearBlockConfirm":"Вся информация блока будет удалена.\nПродолжить?",

"PageSvChangeOnSelected":"Распространить изменения в текущей странице на все выделенные в структуре страницы?",
"PageInputTypeName":"Введите название для нового типа страницы",
"PageTypeSaved":"Тип сохранен",
"PageChangeTypeQuest":"Изменить тип текущей страницы?\nПри смене типа все данные, содержащиеся в текстовых блоках будут утерены!",

"PropTitle":"Свойства",
"PropKey":"Свойство",
"PropValue":"Значение",

"Add":"Добавить",
"AddRowHint":"добавить новую запись",
"Delete":"Удалить",
"DeleteRowHint":"удалить выделенные записи",
"NewRow":"Новая",
"DeleteRowQuest":"Запись будет удалена.\nПродолжить?",
"DeleteRowQuests":"Выделенные записи будут удалены.\nПродолжить?",
"Edit":"Изменить",
"EditRowHint":"редактировать отмеченные записи",

"RefreshTable":"Обновить",
"RefreshTableHint":"обновить таблицу с сервера",

"TableCut":"вырезать выделенные строки в буфер",
"TableCopy":"скопировать выделенные строки в буфер",
"TablePasteUp":"вставить строки из буфера выше текущей строки",
"TablePasteDown":"вставить строки из буфера после текущей строки",

"TablePgDisplayRows":"Показано {0} - {1} из {2}",
"TablePgNoRows":"Записей не найдено",
"TableConnect":"соединить выделенные записи со страницами",

"TreeMenuPublication":"публиковать изменения",
"TreeMenuMakePage":"создать страницу",
"TreeMenuRefresh":"перезагрузить структуру",
"TreeMenuShowAll":"раскрыть все",
"TreeMenuCollapseAll":"свернуть все",
"TreeMenuAccept":"Принять",
"TreeMenuChMode":"Закрыть режим привязки",
"TreeMenuSelectAll":"Выделить все",
"TreeMenuUnselect":"Снять выделение",
"TreeMenuDelete":"Удалить выделенные страницы",
"TreeMenuDeleteConf":"Выделенные страницы будут удалены.\nПродолжить?",
"TreeAddToMap":"Добавить выделенные страницы в карту сайта",
"TreePopupPageCode":"код страницы",
"TreePopupPageOwner":"владелец страницы",
"TreePopupPageLastEditor":"последний редактор",
"TreePopupCut":"Вырезать",
"TreePopupCopy":"Копировать",
"TreePopupCopyAll":"Копировать с подуровнями",
"TreePopupPaste":"Вставить",
"TreePopupMake":"Создать",
"TreePopupDelete":"Удалить",
"TreePopupAccess":"Доступ",
"TreePopupUp":"Поднять",
"TreePopupDown":"Опустить",
"TreePopupPreview":"Просмотр",
"TreePopupEdit":"Редактировать",

"TreeRootPaste":"Вставить из буфера в корневой каталог сайта",
"TreeRootAccess":"Изменить политику доступа у выделенных страниц",
"AccessWinTitle":"Редактирование прав доступа",
"NoAccess":"В доступе отказано!",

"helpMenuEdit":"Редактировать",
"helpMenuDel":"Удалить топик",
"HelpTopicDelAsc":"Текущий справочный текст будет удален.\nПродолжить?",
"EditExt":"Расширенное редактирование",
"ExitAsk":"Завершить текущий сеанс работы?",
"ExitTooltip":"Выйти из системы",
"EmptyText":"Новый",

"MapSaveHint":"Сохранить изменения",
"MapSaved":"Карта сайта сохранена.",

"noAccRead":"У Вас нет прав для просмотра этой страницы",
"Filters":"Фильтры",
"FltrDateBefore":"по",
"FltrDateAfter":"с",
"FltrDateOn":"Указать дату",

"ConnWinTitle":"Связь со страницами",

"vmBack":'Назад',
"vmForw":'Вперед',
"vmRef":'Обновить',
"vmEdit":'Редактирование',
"vmVis":'Просмотр',
"vmEditHint":'Сменить режим редактирование/просмотр',
"vmSave":'Сохранить',
"vmSaveHint":'Сохранить изменения',
"vmBold":'Полужиный',
"vmItalic":'Наклонный',
"vmUnderline":'Подчеркнутый',
"vmFontInc":'Увеличить шрифт',
"vmFontDesc":'Уменьшить шрифт',
"vmOl":'Нумированный список',
"vmUl":'Ненумированный список',
"vmAlLeft":'По левому краю',
"vmAlCentr":'По центру',
"vmAlRight":'По правому краю',
"vmImg":'Вставить рисунок/рисунки',
"vmLink":'Поставить ссылку',
"vmIndent":"Увеличить отступ",
"vmOutdent":"Уменьшить отступ",
"EdtOnlyIE":"Режим визуального редактирования поддерживается только в Internet Explorer",

"vmStyles":"Заданные стили",
"vmEmptyText":"Пустой блок текста",
"vmAdd":"Добавить",
"vmEdit":"Редактировать",
"vmImgBottom":"по нижнему краю",
"vmImgCenter":"по центру",
"vmImgTop":"по верхнему краю",
"vmImgLeft":"по левому краю",
"vmImgRight":"по правому краю",
"vmImgAlt":"альтернативный текст",
"vmImgInsertDlg":"Вставить изображения",
"vmImgAllFormats":"Все форматы (*.*)",

"IO_Copy":"Копирование",
"IO_Stop":"Остановить",
"IO_Progress":"(осталось: %s)",
"IO_Delete":"Удаление",
"IO_DeleteText":"Удаление файлов %s из <b>%s</b>",
"IO_Replace":"Заменить файл<br><br><b>%s:</b> %s?",
"IO_YesToAll":"Да для всех",
"IO_Yes":"Да",
"IO_Skip":"Пропуск",
"IO_SkipAll":"Пропуск всех",
"IO_Cancel":"Отменить",

"Error":"Ошибка",
"Cancel":"Отмена",

"OpenFileDlgTitle":"Открыть файл",

"IO_CopyFromTo":"Копировать %s на %s в",
"IO_CopyFiles":"Копировать файлы (%s) на %s в",
"But_OK":"Да",
"But_Cancel":"Отмена",
"IO_DelConfirm":"Удалить выделенные файлы (%s)?",
"IO_RnmPrompt":"Переименовать файл/директорию",
"IO_Load":"Идет загрузка...",
"IO_SelStore":"Сменить Store...",
"IO_EdtStoreList":"Редактирование списка Store",
"IO_AddStore":"Добавить",
"IO_Save":"Сохранить",
"IO_Delete":"Удалить",
"IO_DelStoreConfirm":"Удалить Store %s?",
"IO_Close":"Закрыть",
"IO_AddFile":"Добавить файл",
"IO_NewDir":"Создать директорию",
"IO_EditStor":"Изм. Store...",
"IO_TB_Back":"Назад",
"IO_TB_Refresh":"Обновить",
"IO_TB_Del":"Удалить файл(ы)",
"IO_TB_Newdir":"Создать директорию",
"IO_TB_Copy":"Копировать выделенный файл(ы)",
"IO_TB_SelAll":"Выделить все",

"IO_ChStor_Name":"Название",
"IO_ChStor_Path":"Сетевой путь",
"IO_ChStor_Passv":"Вкл. пассивный режим (для локальных Store)",
"IO_Open":"Открыть",

"Error":"Ошибка",
"Cancel":"Отмена",

"OpenFileDlgTitle":"Открыть файл",

"XlsRowHint":"Выгрузить данные в табличном виде",

'editorPrepAllTextQ':'Преобразовать весь текст блока?',

'exportButText':'Экспорт',
'exportXlsConfirm':'Сохранение больших объемов данных в формате xls может оказаться невозможным. Продолжить?',

'FirebugMessage':'<b style="color:red">Firebug может замедлить работу CMS. Для более комфортной работы отключите его для этого хоста.</b><br>Для отключения Firebug выполните следующие действия:<br>1. Нажмите на зеленый или красный значок внизу в правом углу окна браузера, чтобы открыть Firebug.<br>2. Нажмите на значок ошибки вверху в левом углу окна Firebug и выберите команду "Отключить Firebug для ...."',

'mkShortCad':'Создать ярлык на рабочем столе',

'dtDeleteShortcut':'Удалить ярлык(и)',
'dtDeleteItems':'Удалить выделенные ярлыки с рабочего стола?',
'dtDeleteItem':'Ярлык будет удален с рабочего стола. Продолжить?',

'FavDel':'Удалить из избранного',
'FavAdd':'Добавить в избранное',
'FavTitle':'Избранное',
'FavMakePanel':'Панель для избранных страниц еще не создана.\nСоздать панель (интерфейс будет перезагружен)?',

'vmViewPublpage':'Посмотреть публичную версию страницы',
'wmToViewMode':'К просмотру',

'CreateLink':'Добавление ссылки на внутреннюю страницу: Ctrl+C на цитируемой странице в структуре, затем, Ctrl+L - в редактируемом тексте',
'Lock cells':'Режим ячеек',
'Clear sets':'Сброс',
'Clean your grid settings?':'Сбросить Ваши настройки просмотра данной таблицы?',
'Clear filters and refresh':'Сбросить фильтры и обновить таблицу',
'Group to filters':'Группировать для фильтров',
'Make child page from file':'Создать страницу из файла MS',
'Change current page content from file':'Заменить текст файлом MS',
'Opera specified':'Особенность броузера Opera',
'In Opera to open popup menus do:<br /><b>Shift+Click</b><br /><i>Show this message next time?</i>':'Для доступа к попап меню используйте комбинацию:<br /><b>Shift+Click</b><br /><i>Выводить это сообщение в следующий раз?</i>',
'Skin was changed. Reload the interface?':'Тема оформления была изменена.<br>Для активации настроек нужно перегрузить страницу. Продолжить?',
'Changing skin':'Смена темы оформления',
'Prepare full text?':'Преобразовать весь текст?',
'Cleane HTML code from Word format':'Очистить HTML-код от форматирования MS Word',
'Change selected pages?':'В структуре выделено несколько страниц.\nСделать изменения во всех выделенных страницах?',
'Some data blocks may be removed. Are you sure?':'Вы изменили количество блоков в существующем шаблоне.\nЛишние блоки на страницах будут удалены.\nПродолжить?',

'Empty text':'Текстовый блок'
};
