function FormatDates(val) {
  var dt = new Date(parseInt(val)*1000);
  return dt.format('d.m.y H:i')
}

TEXTS={
"Exit":"Exit",
"Save":"Save",
"Refresh":"Update",
"Open":"Expand",
"Collapse":"Collapse",
"Close":"Close",
"Preview":"Browsing",
"Garb":"Wastebasket",
"PreviewHint":"Open Preview",
"Settings":"Preferences",
"Moduls":"Modules",
"Structure":"Structure",
"Programms":"Programme",
"Page":"Page",
"Desktop":"Desktop",
"Editor":"Editor",
"Help":"Help",
"AddNodeText":"Enter the name of the page",
"AddNodeDefaultText":"New page",
"DeleteNodeText":"Delete section?",
"DeleteNodesText":"Delete Selected sections?",
"PublicationOk":"Post completed successfully.",
"ClearBlockConfirm":"All information unit will be removed.\nContinue?",
"PageSvChangeOnSelected":"Applying changes to the current page in all selected in the structure of the page?",
"PageInputTypeName":"Enter a name for the new type of page",
"PageTypeSaved":"Tip saved",
"PageChangeTypeQuest":"Change the current page?\nWhen changing the type of all data contained in the text boxes will be utereny!",
"PropTitle":"Properties",
"PropKey":"Property",
"PropValue":"Value",
"Add":"Add",
"AddRowHint":"add a new record",
"Delete":"Remove",
"DeleteRowHint":"delete selected records",
"NewRow":"New",
"DeleteRowQuest":"The list will be removed.\nContinue?",
"DeleteRowQuests":"Marked records will be deleted.\nContinue?",
"Edit":"Change",
"EditRowHint":"edited marked record",
"RefreshTable":"Update",
"RefreshTableHint":"update the table from the server",
"TableCut":"Cut selected rows in the buffer",
"TableCopy":"copy the selected rows in the buffer",
"TablePasteUp":"insert rows from the buffer above the current row",
"TablePasteDown":"insert rows from the buffer after the current line",
"TablePgDisplayRows":"Displaying {0} - {1} of {2}",
"TablePgNoRows":"Record not found",
"TableConnect":"connect to pages dedicated record",
"TreeMenuPublication":"post changes",
"TreeMenuMakePage":"A",
"TreeMenuRefresh":"restart structure",
"TreeMenuShowAll":"reveal all",
"TreeMenuCollapseAll":"all collapse",
"TreeMenuAccept":"Accept",
"TreeMenuChMode":"Close mode of attachment",
"TreeMenuSelectAll":"Select all",
"TreeMenuUnselect":"Clear selected",
"TreeMenuDelete":"Delete Selected Pages",
"TreeMenuDeleteConf":"Marked pages will be deleted.\nContinue?",
"TreeAddToMap":"Add selected page in the site map",
"TreePopupPageCode":"Pages code",
"TreePopupPageOwner":"Pages owner",
"TreePopupPageLastEditor":"last editor",
"TreePopupCut":"Cut",
"TreePopupCopy":"Copy",
"TreePopupCopyAll":"Copy with sublevels",
"TreePopupPaste":"Paste",
"TreePopupMake":"Create",
"TreePopupDelete":"Remove",
"TreePopupAccess":"Access",
"TreePopupUp":"raise the line above",
"TreePopupDown":"Delete",
"TreePopupPreview":"Preview",
"TreePopupEdit":"Edit",
"TreeRootPaste":"Paste buffer to the root directory site",
"TreeRootAccess":"Change policy on access from the allocated pages",
"AccessWinTitle":"Editing access rights",
"helpMenuEdit":"Edit",
"helpMenuDel":"Remove topic",
"HelpTopicDelAsc":"Current background text will be removed.\nContinue?",
"EditExt":"Expanded editing",
"ExitAsk":"End Run of the current work?",
"ExitTooltip":"Exit System",
"EmptyText":"New",
"MapSaveHint":"Save Changes",
"MapSaved":"Sitemap saved.",
"noAccRead":"You are not authorized to view this page",
"Filters":"Filters",
"FltrDateBefore":"Do",
"FltrDateAfter":"After",
"FltrDateOn":"Indicate the date",
"ConnWinTitle":"The link to pages",
"vmBack":"Back",
"vmForw":"Next",
"vmRef":"Update",
"vmEdit":"Edit",
"vmVis":"Browsing",
"vmEditHint":"Change of regime editing / viewing",
"vmSave":"Save",
"vmSaveHint":"Save Changes",
"vmBold":"Poluzhiny",
"vmItalic":"Rotated",
"vmUnderline":"Stressed",
"vmFontInc":"Enlarge font",
"vmFontDesc":"Reduce font",
"vmOl":"Numirovanny list",
"vmUl":"Nenumirovanny list",
"vmAlLeft":"On the left edge",
"vmAlCentr":"Centered",
"vmAlRight":"Align Right",
"vmImg":"Insert picture / images",
"vmLink":"Post link",
"vmIndent":"Indent More",
"vmOutdent":"Less",
"EdtOnlyIE":"Mode visual editing only in Internet Explorer",
"vmStyles":"Assigned styles",
"vmEmptyText":"Empty text block",
"vmAdd":"Add",
"vmImgBottom":"on the bottom",
"vmImgCenter":"at the center",
"vmImgTop":"on the upper edge",
"vmImgLeft":"Left",
"vmImgRight":"on the right side",
"vmImgAlt":"alt",
"vmImgInsertDlg":"Insert image",
"vmImgAllFormats":"All formats (*.*)",
"IO_Copy":"Copying",
"IO_Stop":"Stop",
"IO_Progress":"(left: %s)",
"IO_Delete":"Remove",
"IO_DeleteText":"Deleting files from <b>%s %s</b>",
"IO_Replace":"Replace file <br><br><b>%s:</b> %s?",
"IO_YesToAll":"Yes to all",
"IO_Yes":"Yes",
"IO_Skip":"Skipping",
"IO_SkipAll":"Skipping all",
"IO_Cancel":"Cancel",
"Error":"Error",
"Cancel":"Cancel",
"OpenFileDlgTitle":"Open File",
"IO_CopyFromTo":"Copy %s %s",
"IO_CopyFiles":"Copy files (%s) at %s",
"But_OK":"Yes",
"But_Cancel":"Cancel",
"IO_DelConfirm":"Delete Selected files (%s)?",
"IO_RnmPrompt":"Rename the file / directory",
"IO_Load":"Loading ...",
"IO_SelStore":"Change Store ...",
"IO_EdtStoreList":"Editing list Store",
"IO_AddStore":"Add",
"IO_Save":"Save",
"IO_DelStoreConfirm":"Remove Store %s?",
"IO_Close":"Close",
"IO_AddFile":"Add file",
"IO_NewDir":"Create a directory",
"IO_EditStor":"Edit. Store ...",
"IO_TB_Back":"Back",
"IO_TB_Refresh":"Update",
"IO_TB_Del":"Delete File (%s)",
"IO_TB_Newdir":"Create a directory",
"IO_TB_Copy":"Copy the selected file (%s)",
"IO_TB_SelAll":"Select all",
"IO_ChStor_Name":"Title",
"IO_ChStor_Path":"Network Path",
"IO_ChStor_Passv":"On. Passive mode (for local Store)",
"IO_Open":"Open"
};